#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
if [ -f ~/.bash_aliases ]; then
	source  ~/.bash_aliases
fi

eval $(thefuck --alias)

autoload bashcompinit
bashcompinit
#eval "$(_CASPER_COMPLETE=source ~/cloud-deploy-cli/bin/casper)"
